### ISSUE TITLE
readMix is a big performance drag

### ISSUE THREAD

**Issue by eborden** [pbrisbin/hs-cc-coverage#1]
I played around a bit with performance. It seems the biggest cost center in this lib is `readMix`.

The abbreviated profiling results are:
```
COST CENTRE    MODULE                   SRC                                             %time %alloc

readMix        CC.Coverage.FileCoverage src/CC/Coverage/FileCoverage.hs:78:34-100        84.9   85.2
readTixModules Main                     tix2cc/Main.hs:(56,1)-(58,11)                     9.9   11.1
makeHitMap     CC.Coverage.FileCoverage src/CC/Coverage/FileCoverage.hs:(57,1)-(59,52)    1.1    0.7
```

Nearly all time and allocation is spent in that function. This isn't terribly surprising since `readMix` utilizes `String` based functions, and `Read`/`Show`.

https://www.stackage.org/haddock/lts-11.6/hpc-0.6.0.3/src/Trace-Hpc-Mix.html#readMix

It is a bit of a demoralizing realization. This means either re-implementing `mix` parsing or up-streaming those changes to hpc (not really mutually exclusive). There are likely other wins in `hpc` as well, for example it makes heavy use of `Integer` where `Int` is easily appropriate.

**Comment by eborden** [comment]
It is also possible this is unavoidable and this is IO bound, but concurrency doesn't seem to be providing any leverage.

**Comment by eborden** [comment]
Here are some fun numbers. Forking `hpc` and switching to `serialise` instead of `Read`/`Show`.

```
benchmarking format/serialise
time                 9.450 ms   (9.284 ms .. 9.604 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 9.556 ms   (9.466 ms .. 9.677 ms)
std dev              285.3 μs   (212.2 μs .. 370.0 μs)
             
benchmarking format/read/show
time                 224.4 ms   (204.7 ms .. 242.8 ms)
                     0.997 R²   (0.994 R² .. 1.000 R²)
mean                 216.8 ms   (211.6 ms .. 221.6 ms)
std dev              6.571 ms   (4.076 ms .. 7.688 ms)
variance introduced by outliers: 14% (moderately inflated)
```

**Comment by eborden** [comment]
Also a fun addition, `readMix` utilizes lazy `IO` via `readFile`.

**Comment by eborden** [comment]
Link to the tests: https://github.com/eborden/hpc-serialise

**Comment by pbrisbin** [comment]
I'm archiving this project, so closing all issue. I recommend using one of the hpc-lcov or hpc-codecov packages for [re-]formatting Haskell coverage data for other uses.
